variable "ecs_ami_version" {}
variable "ecs_private_subnet_1" {}
variable "ecs_private_subnet_2" {}
variable "lc_instance_type" {}
variable "environment_name" {}
variable "nulogy_office_ip" {}
variable "public_subnet_1" {}
variable "public_subnet_2" {}
variable "region_cert_arn" {}
variable "route_53_domain" {}
variable "route_53_subdomain" {}
variable "vpc_cidr" {}
variable "vpc_id" {}
