variable "buildkite_agent_token" { }
variable "buildkite_api_access_token" { }
variable "instance_type" { }
variable "key_name" { }
variable "max_size" { }
variable "scale_adjustment" { }
variable "spot_price" { }
variable "stack_config_env" { }
variable "stack_name" { }
variable "stack_template_url" { }
