variable "allocated_storage" {}
variable "db_name" {}
variable "db_password" {}
variable "engine_version" {}
variable "environment_name" {}
variable "instance_class" {}
variable "multi_az" {}
variable "parameter_group_name" {}
variable "production_mode" {}
variable "rds_db_username" {}
variable "rds_private_subnet_1" {}
variable "rds_private_subnet_2" {}
variable "vpc_cidr" {}
variable "vpc_id" {}
